#!/usr/bin/env python3
"""
Verify the new generate_idea() self-improvement proposal path.

Usage:
    python3 ideas/debug_generate_proposal.py [--dry-run]

--dry-run  : build and print the self-improvement topic only (no API calls)
default    : actually call generate_idea() and dump everything to
             ideas/swe_selfimprove_dump.md
"""

import argparse
import sys
from pathlib import Path

IDEAS_DIR = Path(__file__).parent
sys.path.insert(0, str(IDEAS_DIR))
sys.path.insert(0, str(IDEAS_DIR / "systems"))

import log as _log
_log.load_dotenv()

import logging
logging.getLogger().setLevel(logging.INFO)

import swe_agent

SEP = "=" * 70

def banner(title: str, char: str = "=") -> str:
    return f"\n{char * 70}\n## {title}\n{char * 70}\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true",
                        help="Skip actual API call — just build and print the topic")
    args = parser.parse_args()

    champion_version = (IDEAS_DIR / "CURRENT_VERSION").read_text().strip()
    champion_path = IDEAS_DIR / "systems" / f"{champion_version}.py"
    print(f"Champion: {champion_version}")

    # Find comparison report
    reports = sorted(IDEAS_DIR.glob(f"results/compare_*_vs_{champion_version}.json"))
    reports += sorted(IDEAS_DIR.glob(f"results/compare_{champion_version}_vs_*.json"))
    compare_report_path = reports[-1] if reports else None
    print(f"Report  : {compare_report_path}")

    # Build grounded failures
    grounded_failures_str = swe_agent._extract_grounded_failures(compare_report_path, IDEAS_DIR)
    failed_attempts_str = "(none yet — first round)"

    # Build topic
    topic = swe_agent._build_self_improvement_topic(
        champion_version=champion_version,
        champion_path=champion_path,
        grounded_failures_str=grounded_failures_str,
        failed_attempts_str=failed_attempts_str,
    )

    sections = []
    sections.append(f"# SWE Self-Improvement Proposal — {champion_version}\n")
    sections.append("Generated by `debug_generate_proposal.py`.\n")
    sections.append("Shows exactly what the generate_idea() meta-pipeline receives as its topic,\n")
    sections.append("and the full structured proposal it returns for Claude Code to implement.\n")

    sections.append(banner("INPUT: self-improvement topic fed to generate_idea()"))
    sections.append(f"**Size: {len(topic):,} chars ({len(topic)//4:,} tokens est.)**\n")
    sections.append("```\n" + topic + "\n```\n")

    if args.dry_run:
        print("\n[DRY RUN — no API call]\n")
        print(topic)
        out = IDEAS_DIR / "swe_selfimprove_dump.md"
        out.write_text("".join(sections))
        print(f"\nDumped topic to {out}")
        return

    # Real call: generate_idea() → proposal
    print("\nCalling generate_idea() on self-improvement topic...")
    print("(This makes ~13 LLM calls via DeepSeek — takes ~30–60s)\n")

    try:
        idea_raw, idea_fields = swe_agent._call_generate_idea_proposal(
            champion_version=champion_version,
            ideas_dir=IDEAS_DIR,
            topic=topic,
        )
        success = True
        error_msg = None
    except Exception as e:
        success = False
        error_msg = str(e)
        idea_raw = ""
        idea_fields = {}

    # ── Raw output section ──
    sections.append(banner("OUTPUT: raw generate_idea() response"))
    if success:
        sections.append(f"**Size: {len(idea_raw):,} chars**\n")
        sections.append("```\n" + idea_raw + "\n```\n")
    else:
        sections.append(f"**FAILED:** `{error_msg}`\n")

    # ── Parsed fields section ──
    sections.append(banner("OUTPUT: parsed fields"))
    for field in ["idea", "background", "approach", "experiment", "novelty"]:
        val = idea_fields.get(field, "(missing)")
        sections.append(f"### {field.upper()}\n{val}\n")

    # ── Final task_description (what Claude Code receives) ──
    if success:
        diagnosis = idea_fields.get("background", "")
        proposed_fix = idea_fields.get("approach", "")
        expected_impact = idea_fields.get("experiment", "")
        task_description = (
            f"DIAGNOSIS: {diagnosis}\n\n"
            f"PROPOSED FIX: {proposed_fix}\n\n"
            f"EXPECTED IMPACT: {expected_impact}\n\n"
            f"Edit history:\n(none yet)"
        )
        sections.append(banner("FINAL: task_description passed to Claude Code"))
        sections.append(f"**Size: {len(task_description):,} chars**\n")
        sections.append(f"*(IDEA and NOVELTY fields dropped — only BACKGROUND→DIAGNOSIS, APPROACH→PROPOSED FIX, EXPERIMENT→EXPECTED IMPACT)*\n\n")
        sections.append("```\n" + task_description + "\n```\n")

    # Write dump
    out = IDEAS_DIR / "swe_selfimprove_dump.md"
    out.write_text("".join(sections))
    print(f"\n{'SUCCESS' if success else 'FAILED'}")
    if not success:
        print(f"Error: {error_msg}")
    print(f"Dump written to: {out}")

    if success:
        print(f"\nParsed fields: {list(idea_fields.keys())}")
        print(f"  BACKGROUND: {idea_fields.get('background','')[:120]}...")
        print(f"  APPROACH:   {idea_fields.get('approach','')[:120]}...")


if __name__ == "__main__":
    main()
